version: 0.2

env:
  variables:
    BUCKET: "cf-templates-redac"
    STACK_NAME: "redac-infra"
    REGION: "eu-west-1"

phases:
  pre_build:
      - cd voorstel
      - zip voorstel.zip *.js
      - cp voorstel.zip redactionele_controle.zip
      - ls
      - cd ../stamdata
      - zip stamdata.zip *.js
      - ls
  build:
    commands:
      - cd ../infra
      - ls
      - aws cloudformation package --template-file template.yaml --output-template-file serverless-template.yaml --s3-bucket $BUCKET --s3-prefix "redac-infra" --region $REGION
      - ls
      - cd ../stamdata
      - ls
      - aws cloudformation package --template-file template_dm.yaml --output-template-file serverless-template_dm.yaml --s3-bucket $BUCKET --s3-prefix "redac-stamdata_dm" --region $REGION
      - aws cloudformation package --template-file template.yaml --output-template-file serverless-template.yaml --s3-bucket $BUCKET --s3-prefix "redac-stamdata" --region $REGION
      - ls

artifacts:
  type: zip
  files:
    - infra/template.yaml
    - infra/serverless-template.yaml
    - stamdata/template_dm.yaml
    - stamdata/serverless-template_dm.yaml
    - stamdata/template.yaml
    - stamdata/serverless-template.yaml
