version: 0.2

env:
  variables:
    BUCKET: "cf-templates-redac"
    STACK_NAME: "redac-infra"
    REGION: "eu-west-1"

phases:
  install:
    commands:
      - cd infra
      - ls
      - aws cloudformation package --template-file template.yaml --output-template-file serverless-template.yaml --s3-bucket $BUCKET --s3-prefix "redac-infra" --region $REGION
      - ls
      - cd ../voorstel
      - ls
      - aws cloudformation package --template-file template_dm.yaml --output-template-file serverless-template_dm.yaml --s3-bucket $BUCKET --s3-prefix "redac-voorstel-dm" --region $REGION
      - aws cloudformation package --template-file template.yaml --output-template-file serverless-template.yaml --s3-bucket $BUCKET --s3-prefix "redac-voorstel" --region $REGION
      - ls
      
artifacts:
  files:
    - infra/template.yaml
    - infra/serverless-template.yaml
    