version: 0.2

env:
  variables:
    BUCKET: "cf-templates-redac"
    STACK_NAME: "redac-infra"
    REGION: "eu-west-1"

phases:
  install:
    commands:
      - cd infra
      - ls
      - aws cloudformation package --template-file template.yaml --output-template-file serverless-template.yaml --s3-bucket $BUCKET --s3-prefix $STACK_NAME --region $REGION
      
artifacts:
  files:
    - infra/template.yaml
    - infra/serverless-template.yaml
    